apiVersion: v1
kind: Service
metadata:
  name: {{ include "azuresqledge.fullname" . }}
  labels:
    {{- include "azuresqledge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1433
      protocol: TCP
      name: sql
  selector:
    {{- include "azuresqledge.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
